# This template merge config file lists:
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
name = "Keyboard Template"
patterns = ["sje", "sje", "Pite Sami", "MIT"]
rev_id = 17
required = [".gitignore",
            ".github/workflows/docsygen.yml",
            ".taskcluster.yml",
            "Makefile.am",
            "autogen.sh",
            "configure.ac",
            "docs/_config.yml",
            "docs/_includes/toc.html",
            "docs/_layouts/default.html",
            "docs/assets/css/style.scss"]

optional = [".github/workflows/build.yml",
            "AUTHORS",
            "README.md",
            "sje.kbdgen/layouts/sje.yaml",
            "sje.kbdgen/layouts/en.yaml",
            "sje.kbdgen/project.yaml",
            "sje.kbdgen/resources/mac/background.png",
            "sje.kbdgen/resources/mac/icon.sje.png",
            "sje.kbdgen/resources/mac/readme.html",
            "sje.kbdgen/targets/android.yaml",
            "sje.kbdgen/targets/ios.yaml",
            "sje.kbdgen/targets/mac.yaml",
            "sje.kbdgen/targets/win.yaml",
            "docs/index.md",
            "docs/layout.md"]

ignored  = ["LICENSE"]
